name: Hourly Playlist Update

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows you to manually trigger it from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Essential permission to push changes back

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Update Script
        run: python main.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add playlist.m3u
          
          # Check if there are changes before committing to avoid empty commit errors
          if git diff --staged --quiet; then
            print("No changes to commit")
          else
            git commit -m "Auto-update playlist [skip ci]"
            git push
          fi
